// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/common.proto
// Protobuf Java Version: 4.28.3

package com.antinvestor.apis.common.v1;

public interface PaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.v1.Pagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1 [json_name = "count"];</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>int32 page = 2 [json_name = "page"];</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>string start_date = 3 [json_name = "startDate"];</code>
   * @return The startDate.
   */
  java.lang.String getStartDate();
  /**
   * <code>string start_date = 3 [json_name = "startDate"];</code>
   * @return The bytes for startDate.
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string end_date = 4 [json_name = "endDate"];</code>
   * @return The endDate.
   */
  java.lang.String getEndDate();
  /**
   * <code>string end_date = 4 [json_name = "endDate"];</code>
   * @return The bytes for endDate.
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
