// Copyright (c) 2023 Ant Investor Ltd. Licensed under the Apache License 2.0. See https://www.apache.org/licenses/LICENSE-2.0

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/common.proto
// Protobuf Java Version: 4.33.0

package com.antinvestor.apis.common.v1;

@com.google.protobuf.Generated
public interface PaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.v1.Pagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of items per page (limit)
   * </pre>
   *
   * <code>int32 count = 1 [json_name = "count"];</code>
   * @return The count.
   */
  int getCount();

  /**
   * <pre>
   * Page number (0-indexed or 1-indexed depending on service)
   * </pre>
   *
   * <code>int32 page = 2 [json_name = "page"];</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   * Optional: Filter results from this date (RFC3339 format)
   * </pre>
   *
   * <code>string start_date = 3 [json_name = "startDate"];</code>
   * @return The startDate.
   */
  java.lang.String getStartDate();
  /**
   * <pre>
   * Optional: Filter results from this date (RFC3339 format)
   * </pre>
   *
   * <code>string start_date = 3 [json_name = "startDate"];</code>
   * @return The bytes for startDate.
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <pre>
   * Optional: Filter results until this date (RFC3339 format)
   * </pre>
   *
   * <code>string end_date = 4 [json_name = "endDate"];</code>
   * @return The endDate.
   */
  java.lang.String getEndDate();
  /**
   * <pre>
   * Optional: Filter results until this date (RFC3339 format)
   * </pre>
   *
   * <code>string end_date = 4 [json_name = "endDate"];</code>
   * @return The bytes for endDate.
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
