// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/common.proto
// Protobuf Java Version: 4.32.1

package com.antinvestor.apis.common.v1;

/**
 * Protobuf type {@code common.v1.StatusUpdateRequest}
 */
@com.google.protobuf.Generated
public final class StatusUpdateRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:common.v1.StatusUpdateRequest)
    StatusUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      StatusUpdateRequest.class.getName());
  }
  // Use StatusUpdateRequest.newBuilder() to construct.
  private StatusUpdateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StatusUpdateRequest() {
    id_ = "";
    state_ = 0;
    status_ = 0;
    externalId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.antinvestor.apis.common.v1.CommonProto.internal_static_common_v1_StatusUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.antinvestor.apis.common.v1.CommonProto.internal_static_common_v1_StatusUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.antinvestor.apis.common.v1.StatusUpdateRequest.class, com.antinvestor.apis.common.v1.StatusUpdateRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_ = 0;
  /**
   * <code>.common.v1.STATE state = 2 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.common.v1.STATE state = 2 [json_name = "state"];</code>
   * @return The state.
   */
  @java.lang.Override public com.antinvestor.apis.common.v1.STATE getState() {
    com.antinvestor.apis.common.v1.STATE result = com.antinvestor.apis.common.v1.STATE.forNumber(state_);
    return result == null ? com.antinvestor.apis.common.v1.STATE.UNRECOGNIZED : result;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_ = 0;
  /**
   * <code>.common.v1.STATUS status = 3 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.common.v1.STATUS status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.antinvestor.apis.common.v1.STATUS getStatus() {
    com.antinvestor.apis.common.v1.STATUS result = com.antinvestor.apis.common.v1.STATUS.forNumber(status_);
    return result == null ? com.antinvestor.apis.common.v1.STATUS.UNRECOGNIZED : result;
  }

  public static final int EXTERNAL_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object externalId_ = "";
  /**
   * <code>string external_id = 4 [json_name = "externalId"];</code>
   * @return The externalId.
   */
  @java.lang.Override
  public java.lang.String getExternalId() {
    java.lang.Object ref = externalId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      externalId_ = s;
      return s;
    }
  }
  /**
   * <code>string external_id = 4 [json_name = "externalId"];</code>
   * @return The bytes for externalId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExternalIdBytes() {
    java.lang.Object ref = externalId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRAS_FIELD_NUMBER = 5;
  private com.google.protobuf.Struct extras_;
  /**
   * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
   * @return Whether the extras field is set.
   */
  @java.lang.Override
  public boolean hasExtras() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
   * @return The extras.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getExtras() {
    return extras_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extras_;
  }
  /**
   * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getExtrasOrBuilder() {
    return extras_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extras_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (state_ != com.antinvestor.apis.common.v1.STATE.CREATED.getNumber()) {
      output.writeEnum(2, state_);
    }
    if (status_ != com.antinvestor.apis.common.v1.STATUS.UNKNOWN.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, externalId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getExtras());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (state_ != com.antinvestor.apis.common.v1.STATE.CREATED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, state_);
    }
    if (status_ != com.antinvestor.apis.common.v1.STATUS.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, externalId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getExtras());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.antinvestor.apis.common.v1.StatusUpdateRequest)) {
      return super.equals(obj);
    }
    com.antinvestor.apis.common.v1.StatusUpdateRequest other = (com.antinvestor.apis.common.v1.StatusUpdateRequest) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (state_ != other.state_) return false;
    if (status_ != other.status_) return false;
    if (!getExternalId()
        .equals(other.getExternalId())) return false;
    if (hasExtras() != other.hasExtras()) return false;
    if (hasExtras()) {
      if (!getExtras()
          .equals(other.getExtras())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + EXTERNAL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExternalId().hashCode();
    if (hasExtras()) {
      hash = (37 * hash) + EXTRAS_FIELD_NUMBER;
      hash = (53 * hash) + getExtras().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.antinvestor.apis.common.v1.StatusUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.antinvestor.apis.common.v1.StatusUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.v1.StatusUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.v1.StatusUpdateRequest)
      com.antinvestor.apis.common.v1.StatusUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.antinvestor.apis.common.v1.CommonProto.internal_static_common_v1_StatusUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.antinvestor.apis.common.v1.CommonProto.internal_static_common_v1_StatusUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.antinvestor.apis.common.v1.StatusUpdateRequest.class, com.antinvestor.apis.common.v1.StatusUpdateRequest.Builder.class);
    }

    // Construct using com.antinvestor.apis.common.v1.StatusUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetExtrasFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      state_ = 0;
      status_ = 0;
      externalId_ = "";
      extras_ = null;
      if (extrasBuilder_ != null) {
        extrasBuilder_.dispose();
        extrasBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.antinvestor.apis.common.v1.CommonProto.internal_static_common_v1_StatusUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.antinvestor.apis.common.v1.StatusUpdateRequest getDefaultInstanceForType() {
      return com.antinvestor.apis.common.v1.StatusUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.antinvestor.apis.common.v1.StatusUpdateRequest build() {
      com.antinvestor.apis.common.v1.StatusUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.antinvestor.apis.common.v1.StatusUpdateRequest buildPartial() {
      com.antinvestor.apis.common.v1.StatusUpdateRequest result = new com.antinvestor.apis.common.v1.StatusUpdateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.antinvestor.apis.common.v1.StatusUpdateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.externalId_ = externalId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.extras_ = extrasBuilder_ == null
            ? extras_
            : extrasBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.antinvestor.apis.common.v1.StatusUpdateRequest) {
        return mergeFrom((com.antinvestor.apis.common.v1.StatusUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.antinvestor.apis.common.v1.StatusUpdateRequest other) {
      if (other == com.antinvestor.apis.common.v1.StatusUpdateRequest.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getExternalId().isEmpty()) {
        externalId_ = other.externalId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasExtras()) {
        mergeExtras(other.getExtras());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              externalId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetExtrasFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.common.v1.STATE state = 2 [json_name = "state"];</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.common.v1.STATE state = 2 [json_name = "state"];</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.common.v1.STATE state = 2 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public com.antinvestor.apis.common.v1.STATE getState() {
      com.antinvestor.apis.common.v1.STATE result = com.antinvestor.apis.common.v1.STATE.forNumber(state_);
      return result == null ? com.antinvestor.apis.common.v1.STATE.UNRECOGNIZED : result;
    }
    /**
     * <code>.common.v1.STATE state = 2 [json_name = "state"];</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.antinvestor.apis.common.v1.STATE value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.common.v1.STATE state = 2 [json_name = "state"];</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      state_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.common.v1.STATUS status = 3 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.common.v1.STATUS status = 3 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.common.v1.STATUS status = 3 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.antinvestor.apis.common.v1.STATUS getStatus() {
      com.antinvestor.apis.common.v1.STATUS result = com.antinvestor.apis.common.v1.STATUS.forNumber(status_);
      return result == null ? com.antinvestor.apis.common.v1.STATUS.UNRECOGNIZED : result;
    }
    /**
     * <code>.common.v1.STATUS status = 3 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.antinvestor.apis.common.v1.STATUS value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.common.v1.STATUS status = 3 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object externalId_ = "";
    /**
     * <code>string external_id = 4 [json_name = "externalId"];</code>
     * @return The externalId.
     */
    public java.lang.String getExternalId() {
      java.lang.Object ref = externalId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string external_id = 4 [json_name = "externalId"];</code>
     * @return The bytes for externalId.
     */
    public com.google.protobuf.ByteString
        getExternalIdBytes() {
      java.lang.Object ref = externalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string external_id = 4 [json_name = "externalId"];</code>
     * @param value The externalId to set.
     * @return This builder for chaining.
     */
    public Builder setExternalId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      externalId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string external_id = 4 [json_name = "externalId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExternalId() {
      externalId_ = getDefaultInstance().getExternalId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string external_id = 4 [json_name = "externalId"];</code>
     * @param value The bytes for externalId to set.
     * @return This builder for chaining.
     */
    public Builder setExternalIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      externalId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct extras_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> extrasBuilder_;
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     * @return Whether the extras field is set.
     */
    public boolean hasExtras() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     * @return The extras.
     */
    public com.google.protobuf.Struct getExtras() {
      if (extrasBuilder_ == null) {
        return extras_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extras_;
      } else {
        return extrasBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     */
    public Builder setExtras(com.google.protobuf.Struct value) {
      if (extrasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        extras_ = value;
      } else {
        extrasBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     */
    public Builder setExtras(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (extrasBuilder_ == null) {
        extras_ = builderForValue.build();
      } else {
        extrasBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     */
    public Builder mergeExtras(com.google.protobuf.Struct value) {
      if (extrasBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          extras_ != null &&
          extras_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getExtrasBuilder().mergeFrom(value);
        } else {
          extras_ = value;
        }
      } else {
        extrasBuilder_.mergeFrom(value);
      }
      if (extras_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     */
    public Builder clearExtras() {
      bitField0_ = (bitField0_ & ~0x00000010);
      extras_ = null;
      if (extrasBuilder_ != null) {
        extrasBuilder_.dispose();
        extrasBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     */
    public com.google.protobuf.Struct.Builder getExtrasBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetExtrasFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     */
    public com.google.protobuf.StructOrBuilder getExtrasOrBuilder() {
      if (extrasBuilder_ != null) {
        return extrasBuilder_.getMessageOrBuilder();
      } else {
        return extras_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : extras_;
      }
    }
    /**
     * <code>.google.protobuf.Struct extras = 5 [json_name = "extras"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        internalGetExtrasFieldBuilder() {
      if (extrasBuilder_ == null) {
        extrasBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getExtras(),
                getParentForChildren(),
                isClean());
        extras_ = null;
      }
      return extrasBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:common.v1.StatusUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:common.v1.StatusUpdateRequest)
  private static final com.antinvestor.apis.common.v1.StatusUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.antinvestor.apis.common.v1.StatusUpdateRequest();
  }

  public static com.antinvestor.apis.common.v1.StatusUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatusUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<StatusUpdateRequest>() {
    @java.lang.Override
    public StatusUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StatusUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatusUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.antinvestor.apis.common.v1.StatusUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

