name: antinvestor_api_lostid
description: Dart client library for Ant Investor Lostid Service - Lost ID recovery and verification
version: 1.46.2
repository: https://github.com/antinvestor/apis
homepage: https://github.com/antinvestor/apis/tree/main/dart/lostid
issue_tracker: https://github.com/antinvestor/apis/issues

environment:
  sdk: ^3.3.0

dependencies:
  protobuf: ^4.2.0
  connectrpc: ^1.0.0
  fixnum: ^1.1.0
  antinvestor_api_common: ^1.46.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

topics:
  - grpc
  - protobuf
  - api-client
  - lostid
