version: 2
updates:
  # Go modules - common
  - package-ecosystem: "gomod"
    directory: "/go/common"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Go modules - device
  - package-ecosystem: "gomod"
    directory: "/go/device"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Go modules - files
  - package-ecosystem: "gomod"
    directory: "/go/files"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Go modules - ledger
  - package-ecosystem: "gomod"
    directory: "/go/ledger"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Gradle - root project
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Gradle - files subproject
  - package-ecosystem: "gradle"
    directory: "/java/files"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
