version: 2
updates:
  # Go modules - common
  - package-ecosystem: "gomod"
    directories: "/go/*"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Gradle - root project
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 20
    reviewers:
      - "antinvestor/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
