// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partition/v1/partition.proto

// Protobuf Java Version: 3.25.1
package com.antinvestor.apis.partition.v1;

public interface CreatePartitionRoleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:partition.v1.CreatePartitionRoleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string partition_id = 1 [json_name = "partitionId", (.buf.validate.field) = { ... }</code>
   * @return The partitionId.
   */
  java.lang.String getPartitionId();
  /**
   * <code>string partition_id = 1 [json_name = "partitionId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for partitionId.
   */
  com.google.protobuf.ByteString
      getPartitionIdBytes();

  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>map&lt;string, string&gt; properties = 3 [json_name = "properties"];</code>
   */
  int getPropertiesCount();
  /**
   * <code>map&lt;string, string&gt; properties = 3 [json_name = "properties"];</code>
   */
  boolean containsProperties(
      java.lang.String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProperties();
  /**
   * <code>map&lt;string, string&gt; properties = 3 [json_name = "properties"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPropertiesMap();
  /**
   * <code>map&lt;string, string&gt; properties = 3 [json_name = "properties"];</code>
   */
  /* nullable */
java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; properties = 3 [json_name = "properties"];</code>
   */
  java.lang.String getPropertiesOrThrow(
      java.lang.String key);
}
