// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification/v1/notification.proto
// Protobuf Java Version: 4.32.0

package com.antinvestor.apis.notification.v1;

@com.google.protobuf.Generated
public final class NotificationProto {
  private NotificationProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      NotificationProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_Language_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_Language_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_TemplateData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_TemplateData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_Template_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_Template_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_Notification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_Notification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_SearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_SendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_ReleaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_ReleaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_ReleaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_ReleaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_ReceiveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_ReceiveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_ReceiveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_ReceiveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_TemplateSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_TemplateSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_TemplateSearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_TemplateSearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_TemplateSaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_TemplateSaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_v1_TemplateSaveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notification_v1_TemplateSaveResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"notification/v1/notification.proto\022\017no" +
      "tification.v1\032\033buf/validate/validate.pro" +
      "to\032\026common/v1/common.proto\032\034google/api/a" +
      "nnotations.proto\032\034google/protobuf/struct" +
      ".proto\032.protoc-gen-openapiv2/options/ann" +
      "otations.proto\"\221\001\n\010Language\022.\n\002id\030\001 \001(\tB" +
      "\036\272H\033r\026\020\003\030(2\020[0-9a-z_-]{3,20}\330\001\001R\002id\022\022\n\004c" +
      "ode\030\002 \001(\tR\004code\022\022\n\004name\030\003 \001(\tR\004name\022-\n\005e" +
      "xtra\030\004 \001(\0132\027.google.protobuf.StructR\005ext" +
      "ra\"\241\001\n\014TemplateData\022.\n\002id\030\001 \001(\tB\036\272H\033r\026\020\003" +
      "\030(2\020[0-9a-z_-]{3,20}\330\001\001R\002id\022\022\n\004type\030\002 \001(" +
      "\tR\004type\022\026\n\006detail\030\003 \001(\tR\006detail\0225\n\010langu" +
      "age\030\004 \001(\0132\031.notification.v1.LanguageR\010la" +
      "nguage\"\260\001\n\010Template\022.\n\002id\030\001 \001(\tB\036\272H\033r\026\020\003" +
      "\030(2\020[0-9a-z_-]{3,20}\330\001\001R\002id\022\022\n\004name\030\002 \001(" +
      "\tR\004name\0221\n\004data\030\004 \003(\0132\035.notification.v1." +
      "TemplateDataR\004data\022-\n\005extra\030\005 \001(\0132\027.goog" +
      "le.protobuf.StructR\005extra\"\222\005\n\014Notificati" +
      "on\022.\n\002id\030\001 \001(\tB\036\272H\033r\026\020\003\030(2\020[0-9a-z_-]{3," +
      "20}\330\001\001R\002id\022;\n\tparent_id\030\002 \001(\tB\036\272H\033r\026\020\003\030(" +
      "2\020[0-9a-z_-]{3,20}\330\001\001R\010parentId\022.\n\006sourc" +
      "e\030\003 \001(\0132\026.common.v1.ContactLinkR\006source\022" +
      "4\n\trecipient\030\004 \001(\0132\026.common.v1.ContactLi" +
      "nkR\trecipient\022\022\n\004type\030\006 \001(\tR\004type\022\032\n\010tem" +
      "plate\030\007 \001(\tR\010template\0221\n\007payload\030\010 \001(\0132\027" +
      ".google.protobuf.StructR\007payload\022\022\n\004data" +
      "\030\t \001(\tR\004data\022\032\n\010language\030\n \001(\tR\010language" +
      "\022\033\n\tout_bound\030\013 \001(\010R\010outBound\022!\n\014auto_re" +
      "lease\030\014 \001(\010R\013autoRelease\0229\n\010route_id\030\r \001" +
      "(\tB\036\272H\033r\026\020\003\030(2\020[0-9a-z_-]{3,20}\330\001\001R\007rout" +
      "eId\0229\n\006status\030\016 \001(\0132\031.common.v1.StatusRe" +
      "sponseB\006\272H\003\330\001\003R\006status\022/\n\006extras\030\017 \001(\0132\027" +
      ".google.protobuf.StructR\006extras\0225\n\010prior" +
      "ity\030\020 \001(\0162\031.notification.v1.PRIORITYR\010pr" +
      "iority\"C\n\016SearchResponse\0221\n\004data\030\001 \003(\0132\035" +
      ".notification.v1.NotificationR\004data\"@\n\013S" +
      "endRequest\0221\n\004data\030\001 \003(\0132\035.notification." +
      "v1.NotificationR\004data\"=\n\014SendResponse\022-\n" +
      "\004data\030\001 \003(\0132\031.common.v1.StatusResponseR\004" +
      "data\"\\\n\016ReleaseRequest\0220\n\002id\030\001 \003(\tB \272H\035\222" +
      "\001\032\"\030r\026\020\003\030(2\020[0-9a-z_-]{3,20}R\002id\022\030\n\007comm" +
      "ent\030\002 \001(\tR\007comment\"@\n\017ReleaseResponse\022-\n" +
      "\004data\030\001 \003(\0132\031.common.v1.StatusResponseR\004" +
      "data\"C\n\016ReceiveRequest\0221\n\004data\030\001 \003(\0132\035.n" +
      "otification.v1.NotificationR\004data\"@\n\017Rec" +
      "eiveResponse\022-\n\004data\030\001 \003(\0132\031.common.v1.S" +
      "tatusResponseR\004data\"|\n\025TemplateSearchReq" +
      "uest\022\024\n\005query\030\001 \001(\tR\005query\022#\n\rlanguage_c" +
      "ode\030\002 \001(\tR\014languageCode\022\022\n\004page\030\003 \001(\003R\004p" +
      "age\022\024\n\005count\030\004 \001(\005R\005count\"G\n\026TemplateSea" +
      "rchResponse\022-\n\004data\030\001 \003(\0132\031.notification" +
      ".v1.TemplateR\004data\"\252\001\n\023TemplateSaveReque" +
      "st\022\022\n\004name\030\001 \001(\tR\004name\022#\n\rlanguage_code\030" +
      "\002 \001(\tR\014languageCode\022+\n\004data\030\003 \001(\0132\027.goog" +
      "le.protobuf.StructR\004data\022-\n\005extra\030\004 \001(\0132" +
      "\027.google.protobuf.StructR\005extra\"E\n\024Templ" +
      "ateSaveResponse\022-\n\004data\030\001 \001(\0132\031.notifica" +
      "tion.v1.TemplateR\004data*+\n\010PRIORITY\022\010\n\004HI" +
      "GH\020\000\022\007\n\003LOW\020\001\022\014\n\010VERY_LOW\020\0022\304\006\n\023Notifica" +
      "tionService\022W\n\004Send\022\034.notification.v1.Se" +
      "ndRequest\032\035.notification.v1.SendResponse" +
      "\"\020\202\323\344\223\002\n\"\005/send:\001*0\001\022m\n\007Release\022\037.notifi" +
      "cation.v1.ReleaseRequest\032 .notification." +
      "v1.ReleaseResponse\"\035\202\323\344\223\002\027\"\022/send/releas" +
      "e/{id}:\001*0\001\022c\n\007Receive\022\037.notification.v1" +
      ".ReceiveRequest\032 .notification.v1.Receiv" +
      "eResponse\"\023\202\323\344\223\002\r\"\010/receive:\001*0\001\022V\n\006Sear" +
      "ch\022\030.common.v1.SearchRequest\032\037.notificat" +
      "ion.v1.SearchResponse\"\017\202\323\344\223\002\t\022\007/search0\001" +
      "\022S\n\006Status\022\030.common.v1.StatusRequest\032\031.c" +
      "ommon.v1.StatusResponse\"\024\202\323\344\223\002\016\022\014/status" +
      "/{id}\022h\n\014StatusUpdate\022\036.common.v1.Status" +
      "UpdateRequest\032\037.common.v1.StatusUpdateRe" +
      "sponse\"\027\202\323\344\223\002\0212\014/status/{id}:\001*\022v\n\016Templ" +
      "ateSearch\022&.notification.v1.TemplateSear" +
      "chRequest\032\'.notification.v1.TemplateSear" +
      "chResponse\"\021\202\323\344\223\002\013\022\t/template0\001\022q\n\014Templ" +
      "ateSave\022$.notification.v1.TemplateSaveRe" +
      "quest\032%.notification.v1.TemplateSaveResp" +
      "onse\"\024\202\323\344\223\002\016\"\t/template:\001*B\355\003\n$com.antin" +
      "vestor.apis.notification.v1B\021Notificatio" +
      "nProtoP\001ZJgithub.com/antinvestor/apis/go" +
      "/notification/notification/v1;notificati" +
      "onv1\242\002\003NXX\252\002\017Notification.V1\312\002\017Notificat" +
      "ion\\V1\342\002\033Notification\\V1\\GPBMetadata\352\002\020N" +
      "otification::V1\222A\207\002\022t\n\024Notification Serv" +
      "ice\"W\n\020Ant Investor Ltd\022-https://github." +
      "com/antinvestor/service-lostid\032\024info@ant" +
      "investor.com2\0031.0*\002\001\0022\020application/json:" +
      "\020application/jsonZY\nW\n\006bearer\022M\010\002\0228Authe" +
      "ntication token, prefixed by Bearer: Bea" +
      "rer <token>\032\rAuthorization \002b\014\n\n\n\006bearer" +
      "\022\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.antinvestor.apis.common.v1.CommonProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          grpc.gateway.protoc_gen_openapiv2.options.AnnotationsProto.getDescriptor(),
        });
    internal_static_notification_v1_Language_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_notification_v1_Language_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_Language_descriptor,
        new java.lang.String[] { "Id", "Code", "Name", "Extra", });
    internal_static_notification_v1_TemplateData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_notification_v1_TemplateData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_TemplateData_descriptor,
        new java.lang.String[] { "Id", "Type", "Detail", "Language", });
    internal_static_notification_v1_Template_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_notification_v1_Template_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_Template_descriptor,
        new java.lang.String[] { "Id", "Name", "Data", "Extra", });
    internal_static_notification_v1_Notification_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_notification_v1_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_Notification_descriptor,
        new java.lang.String[] { "Id", "ParentId", "Source", "Recipient", "Type", "Template", "Payload", "Data", "Language", "OutBound", "AutoRelease", "RouteId", "Status", "Extras", "Priority", });
    internal_static_notification_v1_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_notification_v1_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_SearchResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_notification_v1_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_notification_v1_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_SendRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_notification_v1_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_notification_v1_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_SendResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_notification_v1_ReleaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_notification_v1_ReleaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_ReleaseRequest_descriptor,
        new java.lang.String[] { "Id", "Comment", });
    internal_static_notification_v1_ReleaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_notification_v1_ReleaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_ReleaseResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_notification_v1_ReceiveRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_notification_v1_ReceiveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_ReceiveRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_notification_v1_ReceiveResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_notification_v1_ReceiveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_ReceiveResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_notification_v1_TemplateSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_notification_v1_TemplateSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_TemplateSearchRequest_descriptor,
        new java.lang.String[] { "Query", "LanguageCode", "Page", "Count", });
    internal_static_notification_v1_TemplateSearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_notification_v1_TemplateSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_TemplateSearchResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_notification_v1_TemplateSaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_notification_v1_TemplateSaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_TemplateSaveRequest_descriptor,
        new java.lang.String[] { "Name", "LanguageCode", "Data", "Extra", });
    internal_static_notification_v1_TemplateSaveResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_notification_v1_TemplateSaveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notification_v1_TemplateSaveResponse_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
    build.buf.validate.ValidateProto.getDescriptor();
    com.antinvestor.apis.common.v1.CommonProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    grpc.gateway.protoc_gen_openapiv2.options.AnnotationsProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(grpc.gateway.protoc_gen_openapiv2.options.AnnotationsProto.openapiv2Swagger);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
