/*
Ant Investor Files

An openAPI 3.0 specification that defines how files are stored and accessed on ant investor products

API version: 1.0.0
Contact: info@antinvestor.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package file_v1

import (
	"encoding/json"
)

// checks if the GetUrlPreviewAuthed200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUrlPreviewAuthed200Response{}

// GetUrlPreviewAuthed200Response struct for GetUrlPreviewAuthed200Response
type GetUrlPreviewAuthed200Response struct {
	// The byte-size of the image. Omitted if there is no image attached.
	MatrixImageSize *int64 `json:"matrix:image:size,omitempty"`
	// An [`mxc://` URI](/client-server-api/#matrix-content-mxc-uris) to the image. Omitted if there is no image.
	OgImage *string `json:"og:image,omitempty"`
}

// NewGetUrlPreviewAuthed200Response instantiates a new GetUrlPreviewAuthed200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUrlPreviewAuthed200Response() *GetUrlPreviewAuthed200Response {
	this := GetUrlPreviewAuthed200Response{}
	return &this
}

// NewGetUrlPreviewAuthed200ResponseWithDefaults instantiates a new GetUrlPreviewAuthed200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUrlPreviewAuthed200ResponseWithDefaults() *GetUrlPreviewAuthed200Response {
	this := GetUrlPreviewAuthed200Response{}
	return &this
}

// GetMatrixImageSize returns the MatrixImageSize field value if set, zero value otherwise.
func (o *GetUrlPreviewAuthed200Response) GetMatrixImageSize() int64 {
	if o == nil || IsNil(o.MatrixImageSize) {
		var ret int64
		return ret
	}
	return *o.MatrixImageSize
}

// GetMatrixImageSizeOk returns a tuple with the MatrixImageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUrlPreviewAuthed200Response) GetMatrixImageSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.MatrixImageSize) {
		return nil, false
	}
	return o.MatrixImageSize, true
}

// HasMatrixImageSize returns a boolean if a field has been set.
func (o *GetUrlPreviewAuthed200Response) HasMatrixImageSize() bool {
	if o != nil && !IsNil(o.MatrixImageSize) {
		return true
	}

	return false
}

// SetMatrixImageSize gets a reference to the given int64 and assigns it to the MatrixImageSize field.
func (o *GetUrlPreviewAuthed200Response) SetMatrixImageSize(v int64) {
	o.MatrixImageSize = &v
}

// GetOgImage returns the OgImage field value if set, zero value otherwise.
func (o *GetUrlPreviewAuthed200Response) GetOgImage() string {
	if o == nil || IsNil(o.OgImage) {
		var ret string
		return ret
	}
	return *o.OgImage
}

// GetOgImageOk returns a tuple with the OgImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUrlPreviewAuthed200Response) GetOgImageOk() (*string, bool) {
	if o == nil || IsNil(o.OgImage) {
		return nil, false
	}
	return o.OgImage, true
}

// HasOgImage returns a boolean if a field has been set.
func (o *GetUrlPreviewAuthed200Response) HasOgImage() bool {
	if o != nil && !IsNil(o.OgImage) {
		return true
	}

	return false
}

// SetOgImage gets a reference to the given string and assigns it to the OgImage field.
func (o *GetUrlPreviewAuthed200Response) SetOgImage(v string) {
	o.OgImage = &v
}

func (o GetUrlPreviewAuthed200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUrlPreviewAuthed200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MatrixImageSize) {
		toSerialize["matrix:image:size"] = o.MatrixImageSize
	}
	if !IsNil(o.OgImage) {
		toSerialize["og:image"] = o.OgImage
	}
	return toSerialize, nil
}

type NullableGetUrlPreviewAuthed200Response struct {
	value *GetUrlPreviewAuthed200Response
	isSet bool
}

func (v NullableGetUrlPreviewAuthed200Response) Get() *GetUrlPreviewAuthed200Response {
	return v.value
}

func (v *NullableGetUrlPreviewAuthed200Response) Set(val *GetUrlPreviewAuthed200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUrlPreviewAuthed200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUrlPreviewAuthed200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUrlPreviewAuthed200Response(val *GetUrlPreviewAuthed200Response) *NullableGetUrlPreviewAuthed200Response {
	return &NullableGetUrlPreviewAuthed200Response{value: val, isSet: true}
}

func (v NullableGetUrlPreviewAuthed200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUrlPreviewAuthed200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
