// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat/v1/chat.proto
// Protobuf Java Version: 4.32.1

package com.antinvestor.apis.chat.v1;

/**
 * <pre>
 * Allowed message types. Extendable via new enum values; clients must ignore unknown values.
 * </pre>
 *
 * Protobuf enum {@code chat.v1.RoomEventType}
 */
@com.google.protobuf.Generated
public enum RoomEventType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MESSAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  MESSAGE_TYPE_UNSPECIFIED(0),
  /**
   * <code>MESSAGE_TYPE_EVENT = 1;</code>
   */
  MESSAGE_TYPE_EVENT(1),
  /**
   * <code>MESSAGE_TYPE_TEXT = 2;</code>
   */
  MESSAGE_TYPE_TEXT(2),
  /**
   * <code>MESSAGE_TYPE_ATTACHMENT = 3;</code>
   */
  MESSAGE_TYPE_ATTACHMENT(3),
  /**
   * <code>MESSAGE_TYPE_REACTION = 7;</code>
   */
  MESSAGE_TYPE_REACTION(7),
  /**
   * <pre>
   * opaque ciphertext
   * </pre>
   *
   * <code>MESSAGE_TYPE_ENCRYPTED = 6;</code>
   */
  MESSAGE_TYPE_ENCRYPTED(6),
  /**
   * <code>MESSAGE_TYPE_SYSTEM = 10;</code>
   */
  MESSAGE_TYPE_SYSTEM(10),
  /**
   * <code>MESSAGE_TYPE_CALL_OFFER = 21;</code>
   */
  MESSAGE_TYPE_CALL_OFFER(21),
  /**
   * <code>MESSAGE_TYPE_CALL_ANSWER = 22;</code>
   */
  MESSAGE_TYPE_CALL_ANSWER(22),
  /**
   * <code>MESSAGE_TYPE_CALL_ICE = 23;</code>
   */
  MESSAGE_TYPE_CALL_ICE(23),
  /**
   * <code>MESSAGE_TYPE_CALL_END = 24;</code>
   */
  MESSAGE_TYPE_CALL_END(24),
  /**
   * <pre>
   * vendor/app specific; metadata must indicate schema
   * </pre>
   *
   * <code>MESSAGE_TYPE_CUSTOM = 100;</code>
   */
  MESSAGE_TYPE_CUSTOM(100),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      RoomEventType.class.getName());
  }
  /**
   * <code>MESSAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int MESSAGE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MESSAGE_TYPE_EVENT = 1;</code>
   */
  public static final int MESSAGE_TYPE_EVENT_VALUE = 1;
  /**
   * <code>MESSAGE_TYPE_TEXT = 2;</code>
   */
  public static final int MESSAGE_TYPE_TEXT_VALUE = 2;
  /**
   * <code>MESSAGE_TYPE_ATTACHMENT = 3;</code>
   */
  public static final int MESSAGE_TYPE_ATTACHMENT_VALUE = 3;
  /**
   * <code>MESSAGE_TYPE_REACTION = 7;</code>
   */
  public static final int MESSAGE_TYPE_REACTION_VALUE = 7;
  /**
   * <pre>
   * opaque ciphertext
   * </pre>
   *
   * <code>MESSAGE_TYPE_ENCRYPTED = 6;</code>
   */
  public static final int MESSAGE_TYPE_ENCRYPTED_VALUE = 6;
  /**
   * <code>MESSAGE_TYPE_SYSTEM = 10;</code>
   */
  public static final int MESSAGE_TYPE_SYSTEM_VALUE = 10;
  /**
   * <code>MESSAGE_TYPE_CALL_OFFER = 21;</code>
   */
  public static final int MESSAGE_TYPE_CALL_OFFER_VALUE = 21;
  /**
   * <code>MESSAGE_TYPE_CALL_ANSWER = 22;</code>
   */
  public static final int MESSAGE_TYPE_CALL_ANSWER_VALUE = 22;
  /**
   * <code>MESSAGE_TYPE_CALL_ICE = 23;</code>
   */
  public static final int MESSAGE_TYPE_CALL_ICE_VALUE = 23;
  /**
   * <code>MESSAGE_TYPE_CALL_END = 24;</code>
   */
  public static final int MESSAGE_TYPE_CALL_END_VALUE = 24;
  /**
   * <pre>
   * vendor/app specific; metadata must indicate schema
   * </pre>
   *
   * <code>MESSAGE_TYPE_CUSTOM = 100;</code>
   */
  public static final int MESSAGE_TYPE_CUSTOM_VALUE = 100;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RoomEventType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RoomEventType forNumber(int value) {
    switch (value) {
      case 0: return MESSAGE_TYPE_UNSPECIFIED;
      case 1: return MESSAGE_TYPE_EVENT;
      case 2: return MESSAGE_TYPE_TEXT;
      case 3: return MESSAGE_TYPE_ATTACHMENT;
      case 7: return MESSAGE_TYPE_REACTION;
      case 6: return MESSAGE_TYPE_ENCRYPTED;
      case 10: return MESSAGE_TYPE_SYSTEM;
      case 21: return MESSAGE_TYPE_CALL_OFFER;
      case 22: return MESSAGE_TYPE_CALL_ANSWER;
      case 23: return MESSAGE_TYPE_CALL_ICE;
      case 24: return MESSAGE_TYPE_CALL_END;
      case 100: return MESSAGE_TYPE_CUSTOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RoomEventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RoomEventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RoomEventType>() {
          public RoomEventType findValueByNumber(int number) {
            return RoomEventType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.antinvestor.apis.chat.v1.ChatProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final RoomEventType[] VALUES = values();

  public static RoomEventType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RoomEventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:chat.v1.RoomEventType)
}

