name: antinvestor_api_property
description: Dart client library for Ant Investor Property Service - Property and asset management
version: 1.46.4
repository: https://github.com/antinvestor/apis
homepage: https://github.com/antinvestor/apis/tree/main/dart/property
issue_tracker: https://github.com/antinvestor/apis/issues

environment:
  sdk: ^3.3.0

dependencies:
  protobuf: ^4.2.0
  connectrpc: ^1.0.0
  fixnum: ^1.1.0
  antinvestor_api_common: ^1.46.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

topics:
  - grpc
  - protobuf
  - api-client
  - property
