// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// source: ocr/v1/ocr.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ocr.v1.RecognizeResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ocr.v1.OCRFile');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr.v1.RecognizeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ocr.v1.RecognizeResponse.repeatedFields_, null);
};
goog.inherits(proto.ocr.v1.RecognizeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr.v1.RecognizeResponse.displayName = 'proto.ocr.v1.RecognizeResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ocr.v1.RecognizeResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr.v1.RecognizeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr.v1.RecognizeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr.v1.RecognizeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr.v1.RecognizeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
referenceId: jspb.Message.getFieldWithDefault(msg, 1, ""),
resultList: jspb.Message.toObjectList(msg.getResultList(),
    proto.ocr.v1.OCRFile.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr.v1.RecognizeResponse}
 */
proto.ocr.v1.RecognizeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr.v1.RecognizeResponse;
  return proto.ocr.v1.RecognizeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr.v1.RecognizeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr.v1.RecognizeResponse}
 */
proto.ocr.v1.RecognizeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReferenceId(value);
      break;
    case 2:
      var value = new proto.ocr.v1.OCRFile;
      reader.readMessage(value,proto.ocr.v1.OCRFile.deserializeBinaryFromReader);
      msg.addResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr.v1.RecognizeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr.v1.RecognizeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr.v1.RecognizeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr.v1.RecognizeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReferenceId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResultList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ocr.v1.OCRFile.serializeBinaryToWriter
    );
  }
};


/**
 * optional string reference_id = 1;
 * @return {string}
 */
proto.ocr.v1.RecognizeResponse.prototype.getReferenceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ocr.v1.RecognizeResponse} returns this
 */
proto.ocr.v1.RecognizeResponse.prototype.setReferenceId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated OCRFile result = 2;
 * @return {!Array<!proto.ocr.v1.OCRFile>}
 */
proto.ocr.v1.RecognizeResponse.prototype.getResultList = function() {
  return /** @type{!Array<!proto.ocr.v1.OCRFile>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ocr.v1.OCRFile, 2));
};


/**
 * @param {!Array<!proto.ocr.v1.OCRFile>} value
 * @return {!proto.ocr.v1.RecognizeResponse} returns this
*/
proto.ocr.v1.RecognizeResponse.prototype.setResultList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ocr.v1.OCRFile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ocr.v1.OCRFile}
 */
proto.ocr.v1.RecognizeResponse.prototype.addResult = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ocr.v1.OCRFile, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ocr.v1.RecognizeResponse} returns this
 */
proto.ocr.v1.RecognizeResponse.prototype.clearResultList = function() {
  return this.setResultList([]);
};


