// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payment/v1/payment.proto
// Protobuf Java Version: 4.32.0

package com.antinvestor.apis.payment.v1;

/**
 * Protobuf type {@code payment.v1.CreatePaymentLinkRequest}
 */
@com.google.protobuf.Generated
public final class CreatePaymentLinkRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:payment.v1.CreatePaymentLinkRequest)
    CreatePaymentLinkRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      CreatePaymentLinkRequest.class.getName());
  }
  // Use CreatePaymentLinkRequest.newBuilder() to construct.
  private CreatePaymentLinkRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreatePaymentLinkRequest() {
    customers_ = java.util.Collections.emptyList();
    notifications_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.antinvestor.apis.payment.v1.PaymentProto.internal_static_payment_v1_CreatePaymentLinkRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.antinvestor.apis.payment.v1.PaymentProto.internal_static_payment_v1_CreatePaymentLinkRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest.class, com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CUSTOMERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.antinvestor.apis.payment.v1.Customer> customers_;
  /**
   * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
   */
  @java.lang.Override
  public java.util.List<com.antinvestor.apis.payment.v1.Customer> getCustomersList() {
    return customers_;
  }
  /**
   * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.antinvestor.apis.payment.v1.CustomerOrBuilder> 
      getCustomersOrBuilderList() {
    return customers_;
  }
  /**
   * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
   */
  @java.lang.Override
  public int getCustomersCount() {
    return customers_.size();
  }
  /**
   * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
   */
  @java.lang.Override
  public com.antinvestor.apis.payment.v1.Customer getCustomers(int index) {
    return customers_.get(index);
  }
  /**
   * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
   */
  @java.lang.Override
  public com.antinvestor.apis.payment.v1.CustomerOrBuilder getCustomersOrBuilder(
      int index) {
    return customers_.get(index);
  }

  public static final int PAYMENT_LINK_FIELD_NUMBER = 2;
  private com.antinvestor.apis.payment.v1.PaymentLink paymentLink_;
  /**
   * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
   * @return Whether the paymentLink field is set.
   */
  @java.lang.Override
  public boolean hasPaymentLink() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
   * @return The paymentLink.
   */
  @java.lang.Override
  public com.antinvestor.apis.payment.v1.PaymentLink getPaymentLink() {
    return paymentLink_ == null ? com.antinvestor.apis.payment.v1.PaymentLink.getDefaultInstance() : paymentLink_;
  }
  /**
   * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
   */
  @java.lang.Override
  public com.antinvestor.apis.payment.v1.PaymentLinkOrBuilder getPaymentLinkOrBuilder() {
    return paymentLink_ == null ? com.antinvestor.apis.payment.v1.PaymentLink.getDefaultInstance() : paymentLink_;
  }

  public static final int NOTIFICATIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList notifications_ =
      emptyIntList();
  private static final     com.google.protobuf.Internal.IntListAdapter.IntConverter<
      com.antinvestor.apis.payment.v1.NotificationType> notifications_converter_ =
          new com.google.protobuf.Internal.IntListAdapter.IntConverter<
              com.antinvestor.apis.payment.v1.NotificationType>() {
            public com.antinvestor.apis.payment.v1.NotificationType convert(int from) {
              com.antinvestor.apis.payment.v1.NotificationType result = com.antinvestor.apis.payment.v1.NotificationType.forNumber(from);
              return result == null ? com.antinvestor.apis.payment.v1.NotificationType.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
   * @return A list containing the notifications.
   */
  @java.lang.Override
  public java.util.List<com.antinvestor.apis.payment.v1.NotificationType> getNotificationsList() {
    return new com.google.protobuf.Internal.IntListAdapter<
        com.antinvestor.apis.payment.v1.NotificationType>(notifications_, notifications_converter_);
  }
  /**
   * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
   * @return The count of notifications.
   */
  @java.lang.Override
  public int getNotificationsCount() {
    return notifications_.size();
  }
  /**
   * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
   * @param index The index of the element to return.
   * @return The notifications at the given index.
   */
  @java.lang.Override
  public com.antinvestor.apis.payment.v1.NotificationType getNotifications(int index) {
    return notifications_converter_.convert(notifications_.getInt(index));
  }
  /**
   * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
   * @return A list containing the enum numeric values on the wire for notifications.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getNotificationsValueList() {
    return notifications_;
  }
  /**
   * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of notifications at the given index.
   */
  @java.lang.Override
  public int getNotificationsValue(int index) {
    return notifications_.getInt(index);
  }
  private int notificationsMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < customers_.size(); i++) {
      output.writeMessage(1, customers_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPaymentLink());
    }
    if (getNotificationsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(notificationsMemoizedSerializedSize);
    }
    for (int i = 0; i < notifications_.size(); i++) {
      output.writeEnumNoTag(notifications_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < customers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, customers_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPaymentLink());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < notifications_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(notifications_.getInt(i));
      }
      size += dataSize;
      if (!getNotificationsList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }notificationsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest)) {
      return super.equals(obj);
    }
    com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest other = (com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest) obj;

    if (!getCustomersList()
        .equals(other.getCustomersList())) return false;
    if (hasPaymentLink() != other.hasPaymentLink()) return false;
    if (hasPaymentLink()) {
      if (!getPaymentLink()
          .equals(other.getPaymentLink())) return false;
    }
    if (!notifications_.equals(other.notifications_)) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCustomersCount() > 0) {
      hash = (37 * hash) + CUSTOMERS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomersList().hashCode();
    }
    if (hasPaymentLink()) {
      hash = (37 * hash) + PAYMENT_LINK_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentLink().hashCode();
    }
    if (getNotificationsCount() > 0) {
      hash = (37 * hash) + NOTIFICATIONS_FIELD_NUMBER;
      hash = (53 * hash) + notifications_.hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code payment.v1.CreatePaymentLinkRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:payment.v1.CreatePaymentLinkRequest)
      com.antinvestor.apis.payment.v1.CreatePaymentLinkRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.antinvestor.apis.payment.v1.PaymentProto.internal_static_payment_v1_CreatePaymentLinkRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.antinvestor.apis.payment.v1.PaymentProto.internal_static_payment_v1_CreatePaymentLinkRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest.class, com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest.Builder.class);
    }

    // Construct using com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCustomersFieldBuilder();
        internalGetPaymentLinkFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (customersBuilder_ == null) {
        customers_ = java.util.Collections.emptyList();
      } else {
        customers_ = null;
        customersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      paymentLink_ = null;
      if (paymentLinkBuilder_ != null) {
        paymentLinkBuilder_.dispose();
        paymentLinkBuilder_ = null;
      }
      notifications_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.antinvestor.apis.payment.v1.PaymentProto.internal_static_payment_v1_CreatePaymentLinkRequest_descriptor;
    }

    @java.lang.Override
    public com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest getDefaultInstanceForType() {
      return com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest build() {
      com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest buildPartial() {
      com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest result = new com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest result) {
      if (customersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          customers_ = java.util.Collections.unmodifiableList(customers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.customers_ = customers_;
      } else {
        result.customers_ = customersBuilder_.build();
      }
    }

    private void buildPartial0(com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.paymentLink_ = paymentLinkBuilder_ == null
            ? paymentLink_
            : paymentLinkBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        notifications_.makeImmutable();
        result.notifications_ = notifications_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest) {
        return mergeFrom((com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest other) {
      if (other == com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest.getDefaultInstance()) return this;
      if (customersBuilder_ == null) {
        if (!other.customers_.isEmpty()) {
          if (customers_.isEmpty()) {
            customers_ = other.customers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCustomersIsMutable();
            customers_.addAll(other.customers_);
          }
          onChanged();
        }
      } else {
        if (!other.customers_.isEmpty()) {
          if (customersBuilder_.isEmpty()) {
            customersBuilder_.dispose();
            customersBuilder_ = null;
            customers_ = other.customers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            customersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCustomersFieldBuilder() : null;
          } else {
            customersBuilder_.addAllMessages(other.customers_);
          }
        }
      }
      if (other.hasPaymentLink()) {
        mergePaymentLink(other.getPaymentLink());
      }
      if (!other.notifications_.isEmpty()) {
        if (notifications_.isEmpty()) {
          notifications_ = other.notifications_;
          notifications_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureNotificationsIsMutable();
          notifications_.addAll(other.notifications_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.antinvestor.apis.payment.v1.Customer m =
                  input.readMessage(
                      com.antinvestor.apis.payment.v1.Customer.parser(),
                      extensionRegistry);
              if (customersBuilder_ == null) {
                ensureCustomersIsMutable();
                customers_.add(m);
              } else {
                customersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetPaymentLinkFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              int tmpRaw = input.readEnum();
              ensureNotificationsIsMutable();
              notifications_.addInt(tmpRaw);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureNotificationsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                notifications_.addInt(input.readEnum());
              }
              input.popLimit(limit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.antinvestor.apis.payment.v1.Customer> customers_ =
      java.util.Collections.emptyList();
    private void ensureCustomersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        customers_ = new java.util.ArrayList<com.antinvestor.apis.payment.v1.Customer>(customers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.antinvestor.apis.payment.v1.Customer, com.antinvestor.apis.payment.v1.Customer.Builder, com.antinvestor.apis.payment.v1.CustomerOrBuilder> customersBuilder_;

    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public java.util.List<com.antinvestor.apis.payment.v1.Customer> getCustomersList() {
      if (customersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(customers_);
      } else {
        return customersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public int getCustomersCount() {
      if (customersBuilder_ == null) {
        return customers_.size();
      } else {
        return customersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public com.antinvestor.apis.payment.v1.Customer getCustomers(int index) {
      if (customersBuilder_ == null) {
        return customers_.get(index);
      } else {
        return customersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder setCustomers(
        int index, com.antinvestor.apis.payment.v1.Customer value) {
      if (customersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomersIsMutable();
        customers_.set(index, value);
        onChanged();
      } else {
        customersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder setCustomers(
        int index, com.antinvestor.apis.payment.v1.Customer.Builder builderForValue) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.set(index, builderForValue.build());
        onChanged();
      } else {
        customersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder addCustomers(com.antinvestor.apis.payment.v1.Customer value) {
      if (customersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomersIsMutable();
        customers_.add(value);
        onChanged();
      } else {
        customersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder addCustomers(
        int index, com.antinvestor.apis.payment.v1.Customer value) {
      if (customersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomersIsMutable();
        customers_.add(index, value);
        onChanged();
      } else {
        customersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder addCustomers(
        com.antinvestor.apis.payment.v1.Customer.Builder builderForValue) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.add(builderForValue.build());
        onChanged();
      } else {
        customersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder addCustomers(
        int index, com.antinvestor.apis.payment.v1.Customer.Builder builderForValue) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.add(index, builderForValue.build());
        onChanged();
      } else {
        customersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder addAllCustomers(
        java.lang.Iterable<? extends com.antinvestor.apis.payment.v1.Customer> values) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, customers_);
        onChanged();
      } else {
        customersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder clearCustomers() {
      if (customersBuilder_ == null) {
        customers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        customersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public Builder removeCustomers(int index) {
      if (customersBuilder_ == null) {
        ensureCustomersIsMutable();
        customers_.remove(index);
        onChanged();
      } else {
        customersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public com.antinvestor.apis.payment.v1.Customer.Builder getCustomersBuilder(
        int index) {
      return internalGetCustomersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public com.antinvestor.apis.payment.v1.CustomerOrBuilder getCustomersOrBuilder(
        int index) {
      if (customersBuilder_ == null) {
        return customers_.get(index);  } else {
        return customersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public java.util.List<? extends com.antinvestor.apis.payment.v1.CustomerOrBuilder> 
         getCustomersOrBuilderList() {
      if (customersBuilder_ != null) {
        return customersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(customers_);
      }
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public com.antinvestor.apis.payment.v1.Customer.Builder addCustomersBuilder() {
      return internalGetCustomersFieldBuilder().addBuilder(
          com.antinvestor.apis.payment.v1.Customer.getDefaultInstance());
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public com.antinvestor.apis.payment.v1.Customer.Builder addCustomersBuilder(
        int index) {
      return internalGetCustomersFieldBuilder().addBuilder(
          index, com.antinvestor.apis.payment.v1.Customer.getDefaultInstance());
    }
    /**
     * <code>repeated .payment.v1.Customer customers = 1 [json_name = "customers"];</code>
     */
    public java.util.List<com.antinvestor.apis.payment.v1.Customer.Builder> 
         getCustomersBuilderList() {
      return internalGetCustomersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.antinvestor.apis.payment.v1.Customer, com.antinvestor.apis.payment.v1.Customer.Builder, com.antinvestor.apis.payment.v1.CustomerOrBuilder> 
        internalGetCustomersFieldBuilder() {
      if (customersBuilder_ == null) {
        customersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.antinvestor.apis.payment.v1.Customer, com.antinvestor.apis.payment.v1.Customer.Builder, com.antinvestor.apis.payment.v1.CustomerOrBuilder>(
                customers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        customers_ = null;
      }
      return customersBuilder_;
    }

    private com.antinvestor.apis.payment.v1.PaymentLink paymentLink_;
    private com.google.protobuf.SingleFieldBuilder<
        com.antinvestor.apis.payment.v1.PaymentLink, com.antinvestor.apis.payment.v1.PaymentLink.Builder, com.antinvestor.apis.payment.v1.PaymentLinkOrBuilder> paymentLinkBuilder_;
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     * @return Whether the paymentLink field is set.
     */
    public boolean hasPaymentLink() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     * @return The paymentLink.
     */
    public com.antinvestor.apis.payment.v1.PaymentLink getPaymentLink() {
      if (paymentLinkBuilder_ == null) {
        return paymentLink_ == null ? com.antinvestor.apis.payment.v1.PaymentLink.getDefaultInstance() : paymentLink_;
      } else {
        return paymentLinkBuilder_.getMessage();
      }
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     */
    public Builder setPaymentLink(com.antinvestor.apis.payment.v1.PaymentLink value) {
      if (paymentLinkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paymentLink_ = value;
      } else {
        paymentLinkBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     */
    public Builder setPaymentLink(
        com.antinvestor.apis.payment.v1.PaymentLink.Builder builderForValue) {
      if (paymentLinkBuilder_ == null) {
        paymentLink_ = builderForValue.build();
      } else {
        paymentLinkBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     */
    public Builder mergePaymentLink(com.antinvestor.apis.payment.v1.PaymentLink value) {
      if (paymentLinkBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          paymentLink_ != null &&
          paymentLink_ != com.antinvestor.apis.payment.v1.PaymentLink.getDefaultInstance()) {
          getPaymentLinkBuilder().mergeFrom(value);
        } else {
          paymentLink_ = value;
        }
      } else {
        paymentLinkBuilder_.mergeFrom(value);
      }
      if (paymentLink_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     */
    public Builder clearPaymentLink() {
      bitField0_ = (bitField0_ & ~0x00000002);
      paymentLink_ = null;
      if (paymentLinkBuilder_ != null) {
        paymentLinkBuilder_.dispose();
        paymentLinkBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     */
    public com.antinvestor.apis.payment.v1.PaymentLink.Builder getPaymentLinkBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetPaymentLinkFieldBuilder().getBuilder();
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     */
    public com.antinvestor.apis.payment.v1.PaymentLinkOrBuilder getPaymentLinkOrBuilder() {
      if (paymentLinkBuilder_ != null) {
        return paymentLinkBuilder_.getMessageOrBuilder();
      } else {
        return paymentLink_ == null ?
            com.antinvestor.apis.payment.v1.PaymentLink.getDefaultInstance() : paymentLink_;
      }
    }
    /**
     * <code>.payment.v1.PaymentLink payment_link = 2 [json_name = "paymentLink"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.antinvestor.apis.payment.v1.PaymentLink, com.antinvestor.apis.payment.v1.PaymentLink.Builder, com.antinvestor.apis.payment.v1.PaymentLinkOrBuilder> 
        internalGetPaymentLinkFieldBuilder() {
      if (paymentLinkBuilder_ == null) {
        paymentLinkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.antinvestor.apis.payment.v1.PaymentLink, com.antinvestor.apis.payment.v1.PaymentLink.Builder, com.antinvestor.apis.payment.v1.PaymentLinkOrBuilder>(
                getPaymentLink(),
                getParentForChildren(),
                isClean());
        paymentLink_ = null;
      }
      return paymentLinkBuilder_;
    }

    private com.google.protobuf.Internal.IntList notifications_ = emptyIntList();
    private void ensureNotificationsIsMutable() {
      if (!notifications_.isModifiable()) {
        notifications_ = makeMutableCopy(notifications_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @return A list containing the notifications.
     */
    public java.util.List<com.antinvestor.apis.payment.v1.NotificationType> getNotificationsList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          com.antinvestor.apis.payment.v1.NotificationType>(notifications_, notifications_converter_);
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @return The count of notifications.
     */
    public int getNotificationsCount() {
      return notifications_.size();
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param index The index of the element to return.
     * @return The notifications at the given index.
     */
    public com.antinvestor.apis.payment.v1.NotificationType getNotifications(int index) {
      return notifications_converter_.convert(notifications_.getInt(index));
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param index The index to set the value at.
     * @param value The notifications to set.
     * @return This builder for chaining.
     */
    public Builder setNotifications(
        int index, com.antinvestor.apis.payment.v1.NotificationType value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNotificationsIsMutable();
      notifications_.setInt(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param value The notifications to add.
     * @return This builder for chaining.
     */
    public Builder addNotifications(com.antinvestor.apis.payment.v1.NotificationType value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNotificationsIsMutable();
      notifications_.addInt(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param values The notifications to add.
     * @return This builder for chaining.
     */
    public Builder addAllNotifications(
        java.lang.Iterable<? extends com.antinvestor.apis.payment.v1.NotificationType> values) {
      ensureNotificationsIsMutable();
      for (com.antinvestor.apis.payment.v1.NotificationType value : values) {
        notifications_.addInt(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNotifications() {
      notifications_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @return A list containing the enum numeric values on the wire for notifications.
     */
    public java.util.List<java.lang.Integer>
    getNotificationsValueList() {
      notifications_.makeImmutable();
      return notifications_;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of notifications at the given index.
     */
    public int getNotificationsValue(int index) {
      return notifications_.getInt(index);
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for notifications to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationsValue(
        int index, int value) {
      ensureNotificationsIsMutable();
      notifications_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param value The enum numeric value on the wire for notifications to add.
     * @return This builder for chaining.
     */
    public Builder addNotificationsValue(int value) {
      ensureNotificationsIsMutable();
      notifications_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .payment.v1.NotificationType notifications = 3 [json_name = "notifications"];</code>
     * @param values The enum numeric values on the wire for notifications to add.
     * @return This builder for chaining.
     */
    public Builder addAllNotificationsValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureNotificationsIsMutable();
      for (int value : values) {
        notifications_.addInt(value);
      }
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:payment.v1.CreatePaymentLinkRequest)
  }

  // @@protoc_insertion_point(class_scope:payment.v1.CreatePaymentLinkRequest)
  private static final com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest();
  }

  public static com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatePaymentLinkRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreatePaymentLinkRequest>() {
    @java.lang.Override
    public CreatePaymentLinkRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreatePaymentLinkRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreatePaymentLinkRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.antinvestor.apis.payment.v1.CreatePaymentLinkRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

