// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/payment.proto

// Protobuf Java Version: 3.25.1
package com.antinvestor.apis.payment.v1;

public final class PaymentProto {
  private PaymentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_Payment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_Payment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_Payment_ExtraEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_Payment_ExtraEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_ReconcileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_ReconcileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_ReconcileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_ReconcileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_SearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_SendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_ReceiveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_ReceiveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_ReceiveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_ReceiveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_ReleaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_ReleaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payment_v1_ReleaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payment_v1_ReleaseResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020v1/payment.proto\022\npayment.v1\032\033buf/vali" +
      "date/validate.proto\032\037google/protobuf/tim" +
      "estamp.proto\032\027google/type/money.proto\032\017v" +
      "1/common.proto\"\203\005\n\007Payment\022\016\n\002id\030\001 \001(\tR\002" +
      "id\022%\n\016transaction_id\030\002 \001(\tR\rtransactionI" +
      "d\022!\n\014reference_id\030\003 \001(\tR\013referenceId\022\031\n\010" +
      "batch_id\030\004 \001(\tR\007batchId\0226\n\027external_tran" +
      "saction_id\030\005 \001(\tR\025externalTransactionId\022" +
      "\024\n\005route\030\006 \001(\tR\005route\022\026\n\006source\030\007 \001(\tR\006s" +
      "ource\022 \n\013destination\030\010 \001(\tR\013destination\022" +
      "*\n\006amount\030\t \001(\0132\022.google.type.MoneyR\006amo" +
      "unt\022&\n\004cost\030\n \001(\0132\022.google.type.MoneyR\004c" +
      "ost\022&\n\005state\030\013 \001(\0162\020.common.v1.STATER\005st" +
      "ate\022)\n\006status\030\014 \001(\0162\021.common.v1.STATUSR\006" +
      "status\022!\n\014date_created\030\r \001(\tR\013dateCreate" +
      "d\022%\n\016date_processed\030\016 \001(\tR\rdateProcessed" +
      "\022\032\n\010outbound\030\017 \001(\010R\010outbound\0224\n\005extra\030\020 " +
      "\003(\0132\036.payment.v1.Payment.ExtraEntryR\005ext" +
      "ra\0328\n\nExtraEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005va" +
      "lue\030\002 \001(\tR\005value:\0028\001\"\340\001\n\020ReconcileReques" +
      "t\0226\n\027external_transaction_id\030\001 \001(\tR\025exte" +
      "rnalTransactionId\022\024\n\005route\030\002 \001(\tR\005route\022" +
      "\032\n\010outbound\030\003 \001(\010R\010outbound\022*\n\006amount\030\004 " +
      "\001(\0132\022.google.type.MoneyR\006amount\022\024\n\005owner" +
      "\030\005 \001(\tR\005owner\022 \n\013countryCode\030\006 \001(\tR\013coun" +
      "tryCode\"\272\001\n\021ReconcileResponse\022\016\n\002id\030\001 \001(" +
      "\tR\002id\022%\n\016transaction_id\030\002 \001(\tR\rtransacti" +
      "onId\022!\n\014reference_id\030\003 \001(\tR\013referenceId\022" +
      ")\n\006status\030\004 \001(\0162\021.common.v1.STATUSR\006stat" +
      "us\022 \n\013description\030\005 \001(\tR\013description\"9\n\016" +
      "SearchResponse\022\'\n\004data\030\001 \003(\0132\023.payment.v" +
      "1.PaymentR\004data\"6\n\013SendRequest\022\'\n\004data\030\001" +
      " \001(\0132\023.payment.v1.PaymentR\004data\"=\n\014SendR" +
      "esponse\022-\n\004data\030\001 \001(\0132\031.common.v1.Status" +
      "ResponseR\004data\"9\n\016ReceiveRequest\022\'\n\004data" +
      "\030\001 \001(\0132\023.payment.v1.PaymentR\004data\"@\n\017Rec" +
      "eiveResponse\022-\n\004data\030\001 \001(\0132\031.common.v1.S" +
      "tatusResponseR\004data\"\221\001\n\016ReleaseRequest\0228" +
      "\n\taccess_id\030\001 \001(\tB\033\272H\030r\026\020\003\030(2\020[0-9a-z_-]" +
      "{3,20}R\010accessId\022+\n\002id\030\002 \001(\tB\033\272H\030r\026\020\003\030(2" +
      "\020[0-9a-z_-]{3,20}R\002id\022\030\n\007comment\030\003 \001(\tR\007" +
      "comment\"@\n\017ReleaseResponse\022-\n\004data\030\001 \001(\013" +
      "2\031.common.v1.StatusResponseR\004data2\357\003\n\016Pa" +
      "ymentService\0229\n\004Send\022\027.payment.v1.SendRe" +
      "quest\032\030.payment.v1.SendResponse\022B\n\007Recei" +
      "ve\022\032.payment.v1.ReceiveRequest\032\033.payment" +
      ".v1.ReceiveResponse\022=\n\006Status\022\030.common.v" +
      "1.StatusRequest\032\031.common.v1.StatusRespon" +
      "se\022O\n\014StatusUpdate\022\036.common.v1.StatusUpd" +
      "ateRequest\032\037.common.v1.StatusUpdateRespo" +
      "nse\022B\n\007Release\022\032.payment.v1.ReleaseReque" +
      "st\032\033.payment.v1.ReleaseResponse\022@\n\006Searc" +
      "h\022\030.common.v1.SearchRequest\032\032.payment.v1" +
      ".SearchResponse0\001\022H\n\tReconcile\022\034.payment" +
      ".v1.ReconcileRequest\032\035.payment.v1.Reconc" +
      "ileResponseB\255\001\n\037com.antinvestor.apis.pay" +
      "ment.v1B\014PaymentProtoP\001Z3github.com/anti" +
      "nvestor/apis/go/payment/v1;paymentv1\242\002\003P" +
      "XX\252\002\nPayment.V1\312\002\nPayment\\V1\342\002\026Payment\\V" +
      "1\\GPBMetadata\352\002\013Payment::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.type.MoneyProto.getDescriptor(),
          com.antinvestor.apis.common.v1.CommonProto.getDescriptor(),
        });
    internal_static_payment_v1_Payment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_payment_v1_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_Payment_descriptor,
        new java.lang.String[] { "Id", "TransactionId", "ReferenceId", "BatchId", "ExternalTransactionId", "Route", "Source", "Destination", "Amount", "Cost", "State", "Status", "DateCreated", "DateProcessed", "Outbound", "Extra", });
    internal_static_payment_v1_Payment_ExtraEntry_descriptor =
      internal_static_payment_v1_Payment_descriptor.getNestedTypes().get(0);
    internal_static_payment_v1_Payment_ExtraEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_Payment_ExtraEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_payment_v1_ReconcileRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_payment_v1_ReconcileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_ReconcileRequest_descriptor,
        new java.lang.String[] { "ExternalTransactionId", "Route", "Outbound", "Amount", "Owner", "CountryCode", });
    internal_static_payment_v1_ReconcileResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_payment_v1_ReconcileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_ReconcileResponse_descriptor,
        new java.lang.String[] { "Id", "TransactionId", "ReferenceId", "Status", "Description", });
    internal_static_payment_v1_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_payment_v1_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_SearchResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_payment_v1_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_payment_v1_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_SendRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_payment_v1_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_payment_v1_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_SendResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_payment_v1_ReceiveRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_payment_v1_ReceiveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_ReceiveRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_payment_v1_ReceiveResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_payment_v1_ReceiveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_ReceiveResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_payment_v1_ReleaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_payment_v1_ReleaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_ReleaseRequest_descriptor,
        new java.lang.String[] { "AccessId", "Id", "Comment", });
    internal_static_payment_v1_ReleaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_payment_v1_ReleaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payment_v1_ReleaseResponse_descriptor,
        new java.lang.String[] { "Data", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.type.MoneyProto.getDescriptor();
    com.antinvestor.apis.common.v1.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
