rootProject.name = "apis"
include("common")
include("chat")
include("ledger")
include("ocr")
include("partition")
include("notification")
include("payment")
include("profile")
include("property")
include("settings")
include("device")
include("files")
