// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: device/v1/device.proto
// Protobuf Java Version: 4.33.0

package com.antinvestor.apis.device.v1;

@com.google.protobuf.Generated
public interface DeviceObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.v1.DeviceObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier for the device
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique identifier for the device
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * User-friendly device name (e.g., "John's iPhone")
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * User-friendly device name (e.g., "John's iPhone")
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Current active session identifier
   * </pre>
   *
   * <code>string session_id = 3 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * Current active session identifier
   * </pre>
   *
   * <code>string session_id = 3 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * Last known IP address
   * </pre>
   *
   * <code>string ip = 4 [json_name = "ip"];</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <pre>
   * Last known IP address
   * </pre>
   *
   * <code>string ip = 4 [json_name = "ip"];</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * User agent string
   * </pre>
   *
   * <code>string user_agent = 5 [json_name = "userAgent"];</code>
   * @return The userAgent.
   */
  java.lang.String getUserAgent();
  /**
   * <pre>
   * User agent string
   * </pre>
   *
   * <code>string user_agent = 5 [json_name = "userAgent"];</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <pre>
   * Operating system and version
   * </pre>
   *
   * <code>string os = 6 [json_name = "os"];</code>
   * @return The os.
   */
  java.lang.String getOs();
  /**
   * <pre>
   * Operating system and version
   * </pre>
   *
   * <code>string os = 6 [json_name = "os"];</code>
   * @return The bytes for os.
   */
  com.google.protobuf.ByteString
      getOsBytes();

  /**
   * <pre>
   * Last activity timestamp (RFC3339)
   * </pre>
   *
   * <code>string last_seen = 7 [json_name = "lastSeen"];</code>
   * @return The lastSeen.
   */
  java.lang.String getLastSeen();
  /**
   * <pre>
   * Last activity timestamp (RFC3339)
   * </pre>
   *
   * <code>string last_seen = 7 [json_name = "lastSeen"];</code>
   * @return The bytes for lastSeen.
   */
  com.google.protobuf.ByteString
      getLastSeenBytes();

  /**
   * <pre>
   * Profile this device is linked to
   * </pre>
   *
   * <code>string profile_id = 8 [json_name = "profileId"];</code>
   * @return The profileId.
   */
  java.lang.String getProfileId();
  /**
   * <pre>
   * Profile this device is linked to
   * </pre>
   *
   * <code>string profile_id = 8 [json_name = "profileId"];</code>
   * @return The bytes for profileId.
   */
  com.google.protobuf.ByteString
      getProfileIdBytes();

  /**
   * <pre>
   * Device locale settings
   * </pre>
   *
   * <code>.device.v1.Locale locale = 9 [json_name = "locale"];</code>
   * @return Whether the locale field is set.
   */
  boolean hasLocale();
  /**
   * <pre>
   * Device locale settings
   * </pre>
   *
   * <code>.device.v1.Locale locale = 9 [json_name = "locale"];</code>
   * @return The locale.
   */
  com.antinvestor.apis.device.v1.Locale getLocale();
  /**
   * <pre>
   * Device locale settings
   * </pre>
   *
   * <code>.device.v1.Locale locale = 9 [json_name = "locale"];</code>
   */
  com.antinvestor.apis.device.v1.LocaleOrBuilder getLocaleOrBuilder();

  /**
   * <pre>
   * Last known geographic location
   * </pre>
   *
   * <code>.google.protobuf.Struct location = 11 [json_name = "location"];</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <pre>
   * Last known geographic location
   * </pre>
   *
   * <code>.google.protobuf.Struct location = 11 [json_name = "location"];</code>
   * @return The location.
   */
  com.google.protobuf.Struct getLocation();
  /**
   * <pre>
   * Last known geographic location
   * </pre>
   *
   * <code>.google.protobuf.Struct location = 11 [json_name = "location"];</code>
   */
  com.google.protobuf.StructOrBuilder getLocationOrBuilder();

  /**
   * <pre>
   * Additional device properties (model, manufacturer, etc.)
   * </pre>
   *
   * <code>.google.protobuf.Struct properties = 15 [json_name = "properties"];</code>
   * @return Whether the properties field is set.
   */
  boolean hasProperties();
  /**
   * <pre>
   * Additional device properties (model, manufacturer, etc.)
   * </pre>
   *
   * <code>.google.protobuf.Struct properties = 15 [json_name = "properties"];</code>
   * @return The properties.
   */
  com.google.protobuf.Struct getProperties();
  /**
   * <pre>
   * Additional device properties (model, manufacturer, etc.)
   * </pre>
   *
   * <code>.google.protobuf.Struct properties = 15 [json_name = "properties"];</code>
   */
  com.google.protobuf.StructOrBuilder getPropertiesOrBuilder();
}
