// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ledger/v1/ledger.proto
// Protobuf Java Version: 4.33.0

package com.antinvestor.apis.ledger.v1;

@com.google.protobuf.Generated
public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ledger.v1.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique account reference/number
   * </pre>
   *
   * <code>string reference = 1 [json_name = "reference"];</code>
   * @return The reference.
   */
  java.lang.String getReference();
  /**
   * <pre>
   * Unique account reference/number
   * </pre>
   *
   * <code>string reference = 1 [json_name = "reference"];</code>
   * @return The bytes for reference.
   */
  com.google.protobuf.ByteString
      getReferenceBytes();

  /**
   * <pre>
   * Ledger this account belongs to
   * </pre>
   *
   * <code>string ledger = 3 [json_name = "ledger"];</code>
   * @return The ledger.
   */
  java.lang.String getLedger();
  /**
   * <pre>
   * Ledger this account belongs to
   * </pre>
   *
   * <code>string ledger = 3 [json_name = "ledger"];</code>
   * @return The bytes for ledger.
   */
  com.google.protobuf.ByteString
      getLedgerBytes();

  /**
   * <pre>
   * Current cleared balance
   * </pre>
   *
   * <code>.google.type.Money balance = 4 [json_name = "balance"];</code>
   * @return Whether the balance field is set.
   */
  boolean hasBalance();
  /**
   * <pre>
   * Current cleared balance
   * </pre>
   *
   * <code>.google.type.Money balance = 4 [json_name = "balance"];</code>
   * @return The balance.
   */
  com.google.type.Money getBalance();
  /**
   * <pre>
   * Current cleared balance
   * </pre>
   *
   * <code>.google.type.Money balance = 4 [json_name = "balance"];</code>
   */
  com.google.type.MoneyOrBuilder getBalanceOrBuilder();

  /**
   * <pre>
   * Additional account metadata (owner, description, etc.)
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 5 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * Additional account metadata (owner, description, etc.)
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 5 [json_name = "data"];</code>
   * @return The data.
   */
  com.google.protobuf.Struct getData();
  /**
   * <pre>
   * Additional account metadata (owner, description, etc.)
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 5 [json_name = "data"];</code>
   */
  com.google.protobuf.StructOrBuilder getDataOrBuilder();

  /**
   * <pre>
   * Balance including uncleared transactions
   * </pre>
   *
   * <code>.google.type.Money uncleared_balance = 6 [json_name = "unclearedBalance"];</code>
   * @return Whether the unclearedBalance field is set.
   */
  boolean hasUnclearedBalance();
  /**
   * <pre>
   * Balance including uncleared transactions
   * </pre>
   *
   * <code>.google.type.Money uncleared_balance = 6 [json_name = "unclearedBalance"];</code>
   * @return The unclearedBalance.
   */
  com.google.type.Money getUnclearedBalance();
  /**
   * <pre>
   * Balance including uncleared transactions
   * </pre>
   *
   * <code>.google.type.Money uncleared_balance = 6 [json_name = "unclearedBalance"];</code>
   */
  com.google.type.MoneyOrBuilder getUnclearedBalanceOrBuilder();

  /**
   * <pre>
   * Amount held in reservations
   * </pre>
   *
   * <code>.google.type.Money reserved_balance = 7 [json_name = "reservedBalance"];</code>
   * @return Whether the reservedBalance field is set.
   */
  boolean hasReservedBalance();
  /**
   * <pre>
   * Amount held in reservations
   * </pre>
   *
   * <code>.google.type.Money reserved_balance = 7 [json_name = "reservedBalance"];</code>
   * @return The reservedBalance.
   */
  com.google.type.Money getReservedBalance();
  /**
   * <pre>
   * Amount held in reservations
   * </pre>
   *
   * <code>.google.type.Money reserved_balance = 7 [json_name = "reservedBalance"];</code>
   */
  com.google.type.MoneyOrBuilder getReservedBalanceOrBuilder();
}
