// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lostid/v1/lostid.proto
// Protobuf Java Version: 4.31.1

package com.antinvestor.apis.lostid.v1;

@com.google.protobuf.Generated
public interface ListTransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lostid.v1.ListTransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .lostid.v1.TransactionItem data = 1 [json_name = "data"];</code>
   */
  java.util.List<com.antinvestor.apis.lostid.v1.TransactionItem> 
      getDataList();
  /**
   * <code>repeated .lostid.v1.TransactionItem data = 1 [json_name = "data"];</code>
   */
  com.antinvestor.apis.lostid.v1.TransactionItem getData(int index);
  /**
   * <code>repeated .lostid.v1.TransactionItem data = 1 [json_name = "data"];</code>
   */
  int getDataCount();
  /**
   * <code>repeated .lostid.v1.TransactionItem data = 1 [json_name = "data"];</code>
   */
  java.util.List<? extends com.antinvestor.apis.lostid.v1.TransactionItemOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .lostid.v1.TransactionItem data = 1 [json_name = "data"];</code>
   */
  com.antinvestor.apis.lostid.v1.TransactionItemOrBuilder getDataOrBuilder(
      int index);
}
