// Copyright 2023-2024 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: profile/v1/profile.proto
// Protobuf Java Version: 4.33.0

package com.antinvestor.apis.profile.v1;

@com.google.protobuf.Generated
public interface RelationshipObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profile.v1.RelationshipObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique relationship ID
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique relationship ID
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Relationship type
   * </pre>
   *
   * <code>.profile.v1.RelationshipType type = 2 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Relationship type
   * </pre>
   *
   * <code>.profile.v1.RelationshipType type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  com.antinvestor.apis.profile.v1.RelationshipType getType();

  /**
   * <pre>
   * Relationship properties
   * </pre>
   *
   * <code>.google.protobuf.Struct properties = 3 [json_name = "properties"];</code>
   * @return Whether the properties field is set.
   */
  boolean hasProperties();
  /**
   * <pre>
   * Relationship properties
   * </pre>
   *
   * <code>.google.protobuf.Struct properties = 3 [json_name = "properties"];</code>
   * @return The properties.
   */
  com.google.protobuf.Struct getProperties();
  /**
   * <pre>
   * Relationship properties
   * </pre>
   *
   * <code>.google.protobuf.Struct properties = 3 [json_name = "properties"];</code>
   */
  com.google.protobuf.StructOrBuilder getPropertiesOrBuilder();

  /**
   * <pre>
   * Child entry in relationship
   * </pre>
   *
   * <code>.profile.v1.EntryItem child_entry = 4 [json_name = "childEntry"];</code>
   * @return Whether the childEntry field is set.
   */
  boolean hasChildEntry();
  /**
   * <pre>
   * Child entry in relationship
   * </pre>
   *
   * <code>.profile.v1.EntryItem child_entry = 4 [json_name = "childEntry"];</code>
   * @return The childEntry.
   */
  com.antinvestor.apis.profile.v1.EntryItem getChildEntry();
  /**
   * <pre>
   * Child entry in relationship
   * </pre>
   *
   * <code>.profile.v1.EntryItem child_entry = 4 [json_name = "childEntry"];</code>
   */
  com.antinvestor.apis.profile.v1.EntryItemOrBuilder getChildEntryOrBuilder();

  /**
   * <pre>
   * Parent entry in relationship
   * </pre>
   *
   * <code>.profile.v1.EntryItem parent_entry = 5 [json_name = "parentEntry"];</code>
   * @return Whether the parentEntry field is set.
   */
  boolean hasParentEntry();
  /**
   * <pre>
   * Parent entry in relationship
   * </pre>
   *
   * <code>.profile.v1.EntryItem parent_entry = 5 [json_name = "parentEntry"];</code>
   * @return The parentEntry.
   */
  com.antinvestor.apis.profile.v1.EntryItem getParentEntry();
  /**
   * <pre>
   * Parent entry in relationship
   * </pre>
   *
   * <code>.profile.v1.EntryItem parent_entry = 5 [json_name = "parentEntry"];</code>
   */
  com.antinvestor.apis.profile.v1.EntryItemOrBuilder getParentEntryOrBuilder();

  /**
   * <pre>
   * Peer profile information
   * </pre>
   *
   * <code>.profile.v1.ProfileObject peer_profile = 6 [json_name = "peerProfile"];</code>
   * @return Whether the peerProfile field is set.
   */
  boolean hasPeerProfile();
  /**
   * <pre>
   * Peer profile information
   * </pre>
   *
   * <code>.profile.v1.ProfileObject peer_profile = 6 [json_name = "peerProfile"];</code>
   * @return The peerProfile.
   */
  com.antinvestor.apis.profile.v1.ProfileObject getPeerProfile();
  /**
   * <pre>
   * Peer profile information
   * </pre>
   *
   * <code>.profile.v1.ProfileObject peer_profile = 6 [json_name = "peerProfile"];</code>
   */
  com.antinvestor.apis.profile.v1.ProfileObjectOrBuilder getPeerProfileOrBuilder();
}
