  # This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish java packages to GH
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    strategy:
      matrix:
        api_module: [ common,device,ledger,lostid,notification,ocr,partition,payment,profile,property,settings,files ]

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup gradlew action
        uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit

      - name: Get the latest tag
        id: get_tags
        run: |
          # Get all tags sorted by creation date (newest first)
          ALL_TAGS=$(git tag --sort=-creatordate | grep "^v" || true)
          echo "All tags found: $ALL_TAGS"
          
          if [[ -z "$ALL_TAGS" ]]; then
            echo "not_enough_tags=true" >> $GITHUB_OUTPUT
            echo "No tags found for repository."
          else
            LATEST_TAG=$(echo "$ALL_TAGS" | head -n 1)
            SECOND_LATEST_TAG=$(echo "$ALL_TAGS" | sed -n '2p')
            
            echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV
            echo "Latest tag: $LATEST_TAG"
            
            if [[ -z "$SECOND_LATEST_TAG" ]]; then
              echo "second_latest_tag=" >> $GITHUB_ENV
              echo "not_enough_tags=true" >> $GITHUB_OUTPUT
              echo "Only one tag found, will publish all modules."
            else
              echo "second_latest_tag=$SECOND_LATEST_TAG" >> $GITHUB_ENV
              echo "Second latest tag: $SECOND_LATEST_TAG"
              echo "not_enough_tags=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Check for changes since the last tag
        if: steps.get_tags.outputs.not_enough_tags == 'false'
        id: java_module_changed
        run: |
          CHANGES=$(git diff --name-only ${{ env.latest_tag }} HEAD | grep 'java/${{ matrix.api_module }}' || true)
          if [[ -n "$CHANGES" ]]; then
            echo "Changes found in java/${{ matrix.api_module }}"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes found in java/${{ matrix.api_module }}"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run publish action
        #if: steps.get_tags.outputs.not_enough_tags == 'true' || steps.java_module_changed.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: java
        run: ./gradlew -Pversion=${{  github.ref_name }} ${{ matrix.api_module }}:publish
