# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish package to npmjs
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    strategy:
      matrix:
        api_module: [ common,ledger ]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd js/${{ matrix.api_module }} && npm ci

      - name: Set output if changes found
        if: steps.get_tags.outputs.not_enough_tags == 'false'
        id: npm_module_changed
        run: |
          if [[ $(git diff --name-only ${{ env.latest_tag }} HEAD | grep 'go/${{ matrix.api_module }}') ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          else
          echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - run: cd js/${{ matrix.api_module }} && npm publish --provenance --access public
        if: steps.npm_module_changed.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}