# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish package to GitHub Packages
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    strategy:
      matrix:
        api_module: [ common,ledger,lostid,notification,ocr,partition,payment,profile,property,settings,files ]

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup gradlew action
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - name: Set output if changes found
        if: steps.get_tags.outputs.not_enough_tags == 'false'
        id: java_module_changed
        run: |
          if [[ $(git diff --name-only ${{ env.latest_tag }} HEAD | grep 'java/${{ matrix.api_module }}') ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          else
          echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run publish action
        if: steps.java_module_changed.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: java
        run: ./gradlew -Pversion=${{  github.ref_name }} ${{ matrix.api_module }}:publish
